apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-app-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voucher-app-auth
  template:
    metadata:
      labels:
        app: voucher-app-auth
    spec:
      containers:
        - name: voucher-app-auth
          image: public.ecr.aws/s6y5a7e8/voucher-app-auth:VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_access_key_id 
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_s3_secret_key_id
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_public_key
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: jwt_private_key
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: AES_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aes_secret
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FRONTEND_URL
            - name: AUDIT_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AUDIT_SQS_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: GOOGLE_CLIENT_ID
            - name: PENTEST_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: PENTEST_ENABLE
            - name: SECURE_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SECURE_ENABLE
            - name: DEMO_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DEMO_ENABLE
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: REDIS_HOST
          resources:
           requests:
             cpu: "50m"
             memory: "200Mi"
           limits:
             cpu: "300m"
             memory: "400Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-k8s-service
spec:
  selector:
    app: voucher-app-auth
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: NodePort
